name: Build APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
